"""Regenerate the sample masks and placeholder facade images.

Committed outputs are the source of truth; this script exists so they can be
changed deliberately rather than being unexplained binaries in the repo.

    python data/samples/make_samples.py

Masks follow the convention in facadekit.segment: light = panel material,
dark = the joint between panels. The facade images are NOT generated by FLUX --
they are flat placeholders so the web app and the `cached` generate adapter
have something to serve before any GPU is wired up.

Why two of the three are irregular
----------------------------------
`grid-regular` is drawn exactly on the catalogue module, so the baseline
legalises it perfectly. That is the trivial case and it is here as a control.

`banded` and `window-punched` carry deterministic jitter, standing in for a
hand-drawn mask or a SAM segmentation of a generated image -- neither of which
lands on a manufacturer's module by luck. They are the honest input: the
baseline visibly fails parts of them, which is the gap the CP-SAT legaliser has
to close. A demo where the naive method scores 100% would hide the thesis.

The jitter is seeded, so the committed PNGs are reproducible byte for byte.
"""

from __future__ import annotations

import random
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
MASKS = HERE / "masks"
FACADES = HERE / "facades"

# 960 x 576 px at the default 12 000 mm facade width = 12.5 mm/px, so a
# 20 x 6 grid lands on 600 x 1200 mm panels: real sizes in the demo catalogue.
PX_W, PX_H = 960, 576
JOINT_PX = 6
INK = 255      # panel material
GAP = 0        # joint
SEED = 20261007


def _blank() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    img = Image.new("L", (PX_W, PX_H), GAP)
    return img, ImageDraw.Draw(img)


def _cell(draw: ImageDraw.ImageDraw, x0: float, y0: float, x1: float, y1: float) -> None:
    """Draw one panel, inset by half a joint on every side."""
    j = JOINT_PX / 2
    if x1 - x0 <= JOINT_PX * 2 or y1 - y0 <= JOINT_PX * 2:
        return
    draw.rectangle([x0 + j, y0 + j, x1 - j, y1 - j], fill=INK)


def _divisions(total: float, count: int, rng: random.Random, jitter: float) -> list[float]:
    """`count` boundaries across `total`, each nudged by up to +/- jitter of a cell.

    Returns count+1 edge positions, first 0 and last `total`.
    """
    step = total / count
    edges = [0.0]
    for i in range(1, count):
        edges.append(step * i + rng.uniform(-jitter, jitter) * step)
    edges.append(total)
    return edges


def mask_grid_regular() -> Image.Image:
    """Control: a plain 20 x 6 grid of exactly 600 x 1200 mm panels."""
    img, draw = _blank()
    cols, rows = 20, 6
    cw, ch = PX_W / cols, PX_H / rows
    for r in range(rows):
        for c in range(cols):
            _cell(draw, c * cw, r * ch, (c + 1) * cw, (r + 1) * ch)
    return img


def mask_banded() -> Image.Image:
    """Six storeys of unequal height, each split into unequal bays."""
    img, draw = _blank()
    rng = random.Random(SEED)
    bands = [20, 10, 20, 13, 10, 20]
    y_edges = _divisions(PX_H, len(bands), rng, jitter=0.18)
    for r, cols in enumerate(bands):
        x_edges = _divisions(PX_W, cols, rng, jitter=0.22)
        for c in range(cols):
            _cell(draw, x_edges[c], y_edges[r], x_edges[c + 1], y_edges[r + 1])
    return img


def mask_window_punched() -> Image.Image:
    """A jittered 20 x 6 grid with two openings punched out."""
    img, draw = _blank()
    rng = random.Random(SEED + 1)
    cols, rows = 20, 6
    x_edges = _divisions(PX_W, cols, rng, jitter=0.15)
    y_edges = _divisions(PX_H, rows, rng, jitter=0.12)
    holes = {(r, c) for r in (1, 2, 3) for c in (4, 5, 6)}
    holes |= {(2, 13), (2, 14), (3, 13), (3, 14)}
    for r in range(rows):
        for c in range(cols):
            if (r, c) in holes:
                continue
            _cell(draw, x_edges[c], y_edges[r], x_edges[c + 1], y_edges[r + 1])
    return img


def facade_placeholder(name: str, mask: Image.Image, tint: tuple[int, int, int]) -> Image.Image:
    """A flat stand-in for a FLUX render: the mask, tinted, clearly labelled."""
    img = Image.new("RGB", (PX_W, PX_H), (28, 32, 40))
    panels = Image.new("RGB", (PX_W, PX_H), tint)
    img.paste(panels, (0, 0), mask)
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, PX_H - 34, PX_W, PX_H], fill=(28, 32, 40))
    draw.text((12, PX_H - 24), f"PLACEHOLDER - not a generated image - {name}", fill=(200, 198, 190))
    return img


def main() -> None:
    MASKS.mkdir(parents=True, exist_ok=True)
    FACADES.mkdir(parents=True, exist_ok=True)

    built = [
        ("grid-regular", mask_grid_regular(), (176, 172, 160)),
        ("banded", mask_banded(), (150, 158, 168)),
        ("window-punched", mask_window_punched(), (168, 150, 138)),
    ]
    for name, mask, tint in built:
        mask.save(MASKS / f"{name}.png")
        facade_placeholder(name, mask, tint).save(FACADES / f"{name}.png")
        print(f"  wrote masks/{name}.png and facades/{name}.png")

    print(f"OK: {len(built)} masks + {len(built)} placeholder facades")


if __name__ == "__main__":
    main()
